services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
      build: .
      command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/project
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db